default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  url: 'postgres://postgres@localhost/dapi_development'

test:
  <<: *default
  url: 'postgres://postgres@localhost/dapi_test'

production:
  <<: *default

